from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class RoutingFeedbackDecision:
    feedback_type: str
    reassignment_type: str | None
    reason: str
    assigned_to: str | None
    assigned_team: str | None
    prior_assigned_to: str | None
    prior_assigned_team: str | None
    metadata: dict[str, Any]


def classify_routing_feedback(
    *,
    previous_assigned_to: str | None,
    previous_assigned_team: str | None,
    new_assigned_to: str | None,
    new_assigned_team: str | None,
    escalation_active: bool,
    policy_changed: bool = False,
    workload_rebalanced: bool = False,
    resolved_without_change: bool = False,
    reason: str | None = None,
) -> RoutingFeedbackDecision:
    note = reason or "routing feedback generated by worker lifecycle"
    changed = (
        previous_assigned_to != new_assigned_to
        or previous_assigned_team != new_assigned_team
    )

    if resolved_without_change:
        return RoutingFeedbackDecision(
            feedback_type="resolved_without_change",
            reassignment_type=None,
            reason=note,
            assigned_to=new_assigned_to,
            assigned_team=new_assigned_team,
            prior_assigned_to=previous_assigned_to,
            prior_assigned_team=previous_assigned_team,
            metadata={"resolved_without_change": True},
        )

    if escalation_active and changed:
        return RoutingFeedbackDecision(
            feedback_type="escalation_reroute",
            reassignment_type="escalation",
            reason=note,
            assigned_to=new_assigned_to,
            assigned_team=new_assigned_team,
            prior_assigned_to=previous_assigned_to,
            prior_assigned_team=previous_assigned_team,
            metadata={"escalation_active": True},
        )

    if workload_rebalanced and changed:
        return RoutingFeedbackDecision(
            feedback_type="workload_rebalance",
            reassignment_type="workload_balance",
            reason=note,
            assigned_to=new_assigned_to,
            assigned_team=new_assigned_team,
            prior_assigned_to=previous_assigned_to,
            prior_assigned_team=previous_assigned_team,
            metadata={"workload_rebalanced": True},
        )

    if policy_changed and changed:
        return RoutingFeedbackDecision(
            feedback_type="manual_reassign",
            reassignment_type="policy_change",
            reason=note,
            assigned_to=new_assigned_to,
            assigned_team=new_assigned_team,
            prior_assigned_to=previous_assigned_to,
            prior_assigned_team=previous_assigned_team,
            metadata={"policy_changed": True},
        )

    if (
        previous_assigned_to is None
        and previous_assigned_team is None
        and (new_assigned_to is not None or new_assigned_team is not None)
    ):
        return RoutingFeedbackDecision(
            feedback_type="accepted",
            reassignment_type=None,
            reason=note,
            assigned_to=new_assigned_to,
            assigned_team=new_assigned_team,
            prior_assigned_to=previous_assigned_to,
            prior_assigned_team=previous_assigned_team,
            metadata={"initial_assignment": True},
        )

    if changed:
        return RoutingFeedbackDecision(
            feedback_type="manual_reassign",
            reassignment_type="manual_override",
            reason=note,
            assigned_to=new_assigned_to,
            assigned_team=new_assigned_team,
            prior_assigned_to=previous_assigned_to,
            prior_assigned_team=previous_assigned_team,
            metadata={},
        )

    return RoutingFeedbackDecision(
        feedback_type="accepted",
        reassignment_type=None,
        reason=note,
        assigned_to=new_assigned_to,
        assigned_team=new_assigned_team,
        prior_assigned_to=previous_assigned_to,
        prior_assigned_team=previous_assigned_team,
        metadata={},
    )
